/**
 * Rule-based deterministic SQL mock parser.
 * Fallback when WebGPU and WASM are both unavailable.
 * Handles common NL patterns with regex heuristics.
 */

const AGGREGATES = {
  count: "COUNT(*)",
  total: "SUM",
  sum: "SUM",
  average: "AVG",
  avg: "AVG",
  max: "MAX",
  maximum: "MAX",
  min: "MIN",
  minimum: "MIN",
};

const FILTER_WORDS = ["where", "with", "having", "whose", "that has", "that have"];
const ORDER_WORDS  = ["order by", "sorted by", "sort by", "ordered by"];
const LIMIT_WORDS  = ["top", "first", "limit"];

function findTable(query, tables) {
  const q = query.toLowerCase();
  // Prefer longer table name match first
  const sorted = [...tables].sort((a, b) => b.name.length - a.name.length);
  for (const t of sorted) {
    const singular = t.name.replace(/s$/, "");
    if (q.includes(t.name.toLowerCase()) || q.includes(singular)) {
      return t;
    }
  }
  return tables[0] ?? null;
}

function findColumn(query, table) {
  if (!table) return null;
  const q = query.toLowerCase();
  const sorted = [...table.columns].sort((a, b) => b.name.length - a.name.length);
  for (const c of sorted) {
    if (q.includes(c.name.toLowerCase())) return c;
  }
  return null;
}

function detectAggregate(query) {
  const q = query.toLowerCase();
  for (const [word, fn] of Object.entries(AGGREGATES)) {
    if (q.includes(word)) return fn;
  }
  return null;
}

function detectLimit(query) {
  const q = query.toLowerCase();
  for (const lw of LIMIT_WORDS) {
    const idx = q.indexOf(lw);
    if (idx !== -1) {
      const after = q.slice(idx + lw.length).trim();
      const num = parseInt(after, 10);
      if (!isNaN(num)) return num;
    }
  }
  const match = q.match(/\b(\d+)\b/);
  return match ? parseInt(match[1], 10) : null;
}

export function mockParse(query, schemaData) {
  const tables = schemaData?.tables ?? [];
  if (tables.length === 0) {
    return "-- Mock parser: no tables defined\nSELECT 1;";
  }

  const table = findTable(query, tables);
  if (!table) return `SELECT * FROM ${tables[0].name} LIMIT 10;`;

  const agg = detectAggregate(query);
  const col = findColumn(query, table);
  const limit = detectLimit(query);

  let selectClause;
  if (agg) {
    if (agg === "COUNT(*)") {
      selectClause = "COUNT(*)";
    } else {
      const targetCol = col ?? table.columns.find((c) => ["INTEGER","FLOAT","BIGINT","DECIMAL"].includes(c.type));
      selectClause = targetCol ? `${agg}(${targetCol.name})` : "COUNT(*)";
    }
  } else if (col) {
    selectClause = col.name;
  } else {
    selectClause = "*";
  }

  let sql = `SELECT ${selectClause}\nFROM ${table.name}`;

  // Simple WHERE detection
  const q = query.toLowerCase();
  for (const fw of FILTER_WORDS) {
    const idx = q.indexOf(fw);
    if (idx !== -1) {
      const filterPart = query.slice(idx + fw.length).trim();
      const filterCol = findColumn(filterPart, table);
      if (filterCol) {
        // Try to extract a value
        const valMatch = filterPart.match(/['"]([^'"]+)['"]/);
        if (valMatch) {
          sql += `\nWHERE ${filterCol.name} = '${valMatch[1]}'`;
        } else {
          const numMatch = filterPart.match(/\b(\d+)\b/);
          if (numMatch) {
            sql += `\nWHERE ${filterCol.name} = ${numMatch[1]}`;
          }
        }
      }
      break;
    }
  }

  if (limit) sql += `\nLIMIT ${limit}`;
  sql += ";";

  return `-- Generated by mock rule-based parser (no AI available)\n${sql}`;
}
